package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// CreateAnnouncement is the resolver for the createAnnouncement field.
func (r *mutationResolver) CreateAnnouncement(ctx context.Context, input biz.CreateAnnouncementInput) (*biz.Announcement, error) {
	return r.announcementService.Create(ctx, input)
}

// DeleteAnnouncement is the resolver for the deleteAnnouncement field.
func (r *mutationResolver) DeleteAnnouncement(ctx context.Context, id objects.GUID) (bool, error) {
	if id.Type != ent.TypeAnnouncement {
		return false, fmt.Errorf("invalid announcement ID")
	}
	if err := r.announcementService.Delete(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context) ([]*biz.Announcement, error) {
	return r.announcementService.List(ctx)
}

// MyAnnouncements is the resolver for the myAnnouncements field.
func (r *queryResolver) MyAnnouncements(ctx context.Context) ([]*biz.Announcement, error) {
	return r.announcementService.ListForCurrentUser(ctx)
}

// AnnouncementRecipientAPIKeys is the resolver for the announcementRecipientAPIKeys field.
func (r *queryResolver) AnnouncementRecipientAPIKeys(ctx context.Context) ([]*biz.AnnouncementRecipientAPIKey, error) {
	return r.announcementService.ListRecipientAPIKeys(ctx)
}
